/**
 * Downloads self-hosted variable fonts (latin + latin-ext subsets) from Google's
 * font CDN and writes a static fonts.css. Run: `node tools/fetch-fonts.mjs`
 * Fonts are committed to /public/fonts so production never depends on a third party.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "fonts");
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const FAMILIES = [
  { family: "Plus Jakarta Sans", slug: "plus-jakarta-sans", range: "200..800", weights: "200 800" },
  { family: "Inter", slug: "inter", range: "100..900", weights: "100 900" },
  { family: "JetBrains Mono", slug: "jetbrains-mono", range: "100..800", weights: "100 800" },
];

const SUBSETS = new Set(["latin", "latin-ext"]);

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const cssOut = [];

  for (const f of FAMILIES) {
    const css = await fetchText(
      `https://fonts.googleapis.com/css2?family=${encodeURIComponent(f.family)}:wght@${f.range}&display=swap`
    );

    // Google emits `/* subset */` immediately before each @font-face; pair them explicitly
    // instead of splitting, so a subset is never mis-attributed to its neighbour.
    const faceRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
    const blocks = [...css.matchAll(faceRe)].map((m) => ({ subset: m[1], body: m[2] }));

    for (const { subset, body: block } of blocks) {
      if (!SUBSETS.has(subset)) continue;

      const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
      const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
      if (!url) continue;

      const file = `${f.slug}-${subset}-var.woff2`;
      const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
      await writeFile(path.join(OUT_DIR, file), buf);

      cssOut.push(
        `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weights};font-display:swap;src:url('/fonts/${file}') format('woff2');${
          unicodeRange ? `unicode-range:${unicodeRange};` : ""
        }}`
      );
      console.log(`wrote public/fonts/${file} (${(buf.length / 1024).toFixed(1)} KB)`);
    }
  }

  await writeFile(
    path.join(ROOT, "src", "styles", "fonts.css"),
    `/* Generated by tools/fetch-fonts.mjs — self-hosted variable fonts. */\n${cssOut.join("\n")}\n`
  );
  console.log(`wrote src/styles/fonts.css (${cssOut.length} faces)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
